apiVersion: eventbridge.services.k8s.aws/v1alpha1
kind: Endpoint
metadata:
  name: endpoint-01-eu-central-1
  annotations:
    services.k8s.aws/region: eu-central-1
spec:
  name: endpoint-01
  description: "ACK EventBridge Endpoint with disabled replication and without role arn"
  eventBuses:
    - eventBusARN: arn:aws:events:eu-central-1:331505801289:event-bus/bus-01
    - eventBusARN: arn:aws:events:eu-west-1:331505801289:event-bus/bus-01
  routingConfig:
    failoverConfig:
      primary:
        healthCheck: arn:aws:route53:::healthcheck/fdc2d14a-c152-499f-ab71-3d1c57eee075
      secondary:
        route: eu-west-1
  replicationConfig:
    state: DISABLED
